# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Laos School' do
pod 'Firebase'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
pod 'GoogleTagManager', '~> 5.0'
end

